// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5fvwZlsRj1Ltp8IWVAiCrwcD5Rexa1LA',
    appId: '1:1682898445:android:73a0b5c65587f4215e9f44',
    messagingSenderId: '1682898445',
    projectId: 'trials-b0b95',
    storageBucket: 'trials-b0b95.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACw2dknC-cWv3eBYiWpwS4-MyX7MDDMB8',
    appId: '1:1682898445:ios:9ad51d46e676fd0e5e9f44',
    messagingSenderId: '1682898445',
    projectId: 'trials-b0b95',
    storageBucket: 'trials-b0b95.appspot.com',
    iosBundleId: 'com.bscs3b.g3.interactiveZooCatalogUsingQrCode',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAq8c1JDRnLrBv5KdeC6_O-S5IBOkdy2-w',
    appId: '1:1682898445:web:8eedb05e4b50c8be5e9f44',
    messagingSenderId: '1682898445',
    projectId: 'trials-b0b95',
    authDomain: 'trials-b0b95.firebaseapp.com',
    storageBucket: 'trials-b0b95.appspot.com',
    measurementId: 'G-DL41B0CMXD',
  );

}